### ISSUE TITLE
Load YAML files in Analysis.__init__

### ISSUE THREAD

**Issue by milanbhakta** [analytic-alchemists/alchemistpkg#11]
- setup __init__ to capture config files

**Comment by mschumak** [comment]
Loading the three levels of yml files when Analysis is used from a package installation isn't working:

Loading configs/system_config.yml
Traceback (most recent call last):
  File "/mnt/c/Users/masch/Documents/MLcert/ressoft/temp/test.py", line 5, in <module>
    a = A.Analysis("alchemistpkg/analysis_config.yml")
  File "/home/mschumak/.local/lib/python3.10/site-packages/alchemistpkg/Analysis.py", line 46, in __init__
    with open(path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/system_config.yml'

**Comment by milanbhakta** [comment]
Loading the file will work if you pass it as ../configs/system_config.yml , ../configs/user_config.yml and passing ../configs/analysis_config.yml as path in initialization of class

**Comment by mschumak** [comment]
I'm not sure why the specifications don't have the file argument for Analysis() as optional. If the input file is invalid, should it default to one of the pre-existing files?

**Comment by rfong1** [comment]
I can use a try/except step do input defaults for the files.
I could go as far as to include a default dictionary in the code.

**Comment by mschumak** [comment]
Yes, try/except on the input and the yml files is the right approach. A final default dictionary is a good idea.

**Comment by milanbhakta** [comment]
Completed
