### ISSUE TITLE
Access NYT API and test query

### ISSUE THREAD

**Issue by mschumak** [analytic-alchemists/alchemistpkg#14]
We decided on the New York Times API, and their example query for searching the front page for a given word.
https://developer.nytimes.com/docs/articlesearch-product/1/overview

"Find articles with the word Pokemon that were on the print paper's front page.
fq=Pokemon AND print_page:1 AND (print_section:("A", "1") OR (!_exists_:print_section))"

**Comment by milanbhakta** [comment]
COPY OF implement.load_data()

**Comment by mschumak** [comment]
Complete
